### ISSUE TITLE
Root access

### ISSUE THREAD

**Issue by wblech** [juanlamarao/42_remote_dev_env#4]
I'm trying to use `su -` command, but it keeps asking for a password. Does anyone know the password for root access?

**Comment by juanlamarao** [comment]
the root password wasn't set, but you can (after running the 'run-container.sh'), run `docker exec remote_42_ctn some_command`, changing _some\_command_ for your command, and it will run as root.
But thanks for notice that, I'll change it soon :smiley:

**Comment by juanlamarao** [comment]
I closed this issue by mistake kkk

**Comment by wblech** [comment]
I was trying to put a command in deploy.sh to set a password. I tried using the passwd command. But ir didn't work.

I wrote this command:

`passwd teste`

**teste** was supposed to be the password but I got an error **teste is not a user**

**Comment by juanlamarao** [comment]
The `passwd` command asks for password input in interactive mode.
I just added to the run_container.sh and src/entrypoint.sh a variable that will be exported to the container as ROOT_PASSWD.
The command to change the root password was `echo "root:$ROOT_PASSWD" | chpasswd`
