### ISSUE TITLE
Norminette

### ISSUE THREAD

**Issue by wblech** [juanlamarao/42_remote_dev_env#5]
I am trying to set norminette in the image. I am changing the **deploy.sh** file. But I couldn't get it fixed.

Those are my changes:

I have added a variable in package install

`L_PKG_RUBY="ruby ruby-bundler ruby-dev build-essential"`

Than I added it to the install package command

`apt-get install -y --no-install-recommends apt-utils=1.8.2 2> /dev/null
echo "$L_PKG_MAN" | xargs apt-get install -y --no-install-recommends
echo "$L_PKG_DEPN" "$L_PKG_DEBG" "$L_PKG_VIM" "$L_PKG_EMACS" "$L_PKG_RUBY" "$L_PKG_OTHERS" | \
	xargs apt-get install -y --no-install-recommends`

After that I updated the bundle

`gem install bundler:2.1.2` 

The problem here is that I can't install bundle as a **root**. If I do that the bundle will crash but if I try to install as the user **me** it says I don't have permission.

I can't figure out how to install the bundler version as the **me** user.

In the end of the file I added more commands but they won't work if I can't install the bundler version:

```
# norminette config
bundle update --bundler
cp -rf norminette ~/.norminette
cd ~/.norminette/
bundle
echo 'alias norminette="~/.norminette/norminette.rb"' >> ~/.profile
source ~/.profile
cd
```
The norminette folder is the one at this repository

`https://github.com/42sp/norminette-client`

Finally I changed the final command to remove the **norminette** folder

```
# remove unecessary files
rm -rf deploy.sh vimrc 42header.vim 42header_emacs su-exec entrypoint.sh bashrc locale.gen norminette
```

**Comment by juanlamarao** [comment]
I think you can copy the git repository to the image and run `gem install bundler:2.1.2` (at deploy.sh) and change its ownership to `me` user (at entrypoint.sh).
Don't need to add the build-essentials to your L_PKG_RBY because it is already in L_PKG_DEPN.
all this as root :arrow_up: 
it will work with _'me'_ user when executing `./norminette_path/norminette.rb` (theoretically) :smile: 

fell free to make a pull request to this issue :octocat:

**Comment by wblech** [comment]
ok. I'll try to fix and pull the change.

**Comment by wblech** [comment]
So I've managed to install bundler, and the norminette. I exported to the .profile the alias. The only thing that is not working now is the the command `source ~/.profile`

Couldn't find why. Any ideia?

**Comment by juanlamarao** [comment]
Odd... But since we have the _srcs/bashrc_ you can just add your alias to it. And it will be copied at the _deploy.sh_ stage
